config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  get 'braintree/new'
  get 'listing/index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"


  get 'welcome/index'

  root 'welcome#index'

  get 'listings/index'
  resources :listings, controller: "listings" do
    resources :reservations, except: :index
  end
  resources :reservations, only:[:index]
  get '/listings/verify/:id' => 'listings#verify', as: "verify"

  post 'braintree/checkout'

  get "search" => "search#index"


  # get "/listings/:id/reservation" => "reservations#show", as: "reservation"
  # post "/listings/:id/reservation" => "reservation#crceate", as: "post_reservation"

  # resources :reservations, controller: "reservations" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, controller: "users"
  get '/users/:id' => "users#show"
end

app/models/listing.rb
class Listing < ApplicationRecord
  mount_uploaders :avatars, AvatarUploader
  has_many :reservations, dependent: :destroy
  belongs_to :user

  scope :city, -> (city) { where("city like ?", "%#{city}%") }
  scope :room_number, -> (room_number) { where room_number: room_number }
  scope :property_type, -> (property_type) { where("property_type ilike ?", "#{property_type}") }
  scope :bathroom_number, -> (bathroom_number) { where bathroom_number: bathroom_number }
  scope :namesearch, -> (namesearch) { where("name like ?", "%#{namesearch}%")}
  scope :price_range, -> (from,to) {where ("price >= ? AND price <= ?"), from, to}

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
  	@listing = Listing.page(params[:page]).per(12)

    respond_to do |format|
      format.html
      format.js { render :layout => false, json: @listing }
    end
    
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
  end

  def edit
  	@listing = Listing.find(params[:id])
  	
  end

  def update
  	@listing = Listing.find(params[:id])
  	if current_user == nil || (current_user.access_level == "customer" && @listing.user_id != current_user.id)
  	 	flash[:notice] = "this list is not yours"
  	 	redirect_back fallback_location: @listing
  	else
	  if @listing.update(listing_params) 
	    redirect_to @listing
	  else
	    render 'edit'
	  end
	end
  end

  def destroy
	  @listing = Listing.find(params[:id])
	  if current_user == nil || (current_user.access_level == "customer" && @listing.user_id != current_user.id)
  	 	flash[:notice] = "This list is not yours"
  	 	redirect_back fallback_location: @listing

  	  else
	  @listing.destroy
	 
	  redirect_to listings_path
	 end
  end

  def verify
  	@listing = Listing.find(params[:id])

  	@listing.update(verification: true)

  	redirect_back fallback_location: @listing

  end

  def create
  
  	@listing = Listing.new(listing_params)
 	  @listing.user_id = current_user.id
  	@listing.save
  	redirect_to @listing
  end

  private
  def listing_params
    params.require(:listing).permit(:name, :property_type, :place_type, :country, :city,:room_number, :bathroom_number, :street, :area, :price, :guest, {avatars: []})
  end 

end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/listings/_listing.html.erb
<% @listing.order(updated_at: :desc).each do |listing| %>
  <div class="col-4 mb-4">
    <div class="card">
      <% if listing.avatars != [] %>
        <img class="card-img-top listing" style="width: 100%" src="<%= listing.avatars[0] %>" alt="Card image cap">
      <% end %>
      <div class="card-body">
        <h5 class="card-title text-capitalize"><%= listing.name %></h5>
        <p class="card-text"><strong>City: </strong><span class="text-capitalize"><%= listing.city %></span></p>
        <p class="card-text"><strong>Number of Rooms: </strong><span class="text-capitalize"><%= listing.room_number %></span></p>
        <p class="card-text"><strong>Area: </strong><span class="text-capitalize"><%= listing.area %></span></p>
        <p class="card-text"><strong>Belongs to: </strong><span class="text-capitalize"><%= listing.user.username %></span></p>
        <div class="text-capitalize">
          <%= link_to 'Read more', listing_path(listing), :class => "btn btn-primary btn-block" %>
          <%= link_to 'Edit', edit_listing_path(listing), :class => "btn btn-warning btn-block" %>
          <%= link_to 'Destroy', listing_path(listing), :class => "btn btn-danger btn-block", method: :delete, data: { confirm: 'Are you sure?' } %>
          <%= link_to "Make a reservation", new_listing_reservation_path(listing), :class => "btn btn-success btn-block" %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/listings/edit.erb
<div class="container mt-3">
  <h1 class="text-center">Edit Listing</h1>

  <%= form_with(model: @listing, local: true) do |form| %>
    <div class="mt-3">
      <h3><%= form.label :name %>:</h3>
      <%= form.text_field :name, :class => "form-control", :required => true %>
    </div>

    <div class="mt-3">
      <h3><%= form.label :property_type %>:</h3>
      <%= form.text_field :property_type, :class => "form-control", :required => true %>
    </div>

    <div class="mt-3">
      <h3><%= form.label :country %>:</h3>
      <%= form.text_field :country, :class => "form-control", :required => true %>
    </div>
   
    <div class="mt-3">
      <h3><%= form.label :city %>:</h3>
      <%= form.text_field :city, :class => "form-control", :required => true %>
    </div>

    <div class="mt-3">
      <h3><%= form.label :number_of_rooms %>:</h3>
      <%= form.text_field :room_number, :class => "form-control", :required => true %>
    </div>
   
    <div class="mt-3">
      <h3><%= form.label :number_of_bathrooms %>:</h3>
      <%= form.text_field :bathroom_number, :class => "form-control", :required => true %>
    </div>

     <div class="mt-3">
      <h3><%= form.label :street %>:</h3>
      <%= form.text_field :street, :class => "form-control", :required => true %>
    </div>

    <div class="mt-3">
      <h3><%= form.label :area %>:</h3>
      <%= form.text_field :area, :class => "form-control", :required => true %>
    </div>
   
    <div class="mt-3">
      <h3><%= form.label :price %>:</h3>
      <%= form.text_field :price, :class => "form-control", :required => true %>
    </div>

    <div class="mt-3">
      <h3><%= form.label :guest %>:</h3>
      <%= form.text_field :guest, :class => "form-control", :required => true %>
    </div>

    <div class="mt-3">
      <h6><%= form.file_field :avatars, multiple: true %></h6>
    </div>
   
    <div class="pt-2 my-4">
      <%= form.submit :class => "btn btn-primary" %>
      <%= link_to 'Back', listings_path, :class => "pl-2" %>
    </div>

    
  <% end %>

</div>

app/views/listings/index.html.erb
<div class="container my-3">
  <h1 class="text-center">All Listings</h1>

  <div id="listings" class="row">
    <%= render "listing" %>
  </div>

  <div id="paginator">
  	<%= paginate @listing, :remote => true %>
  </div>
</div>

app/views/listings/index.js.erb
$('#listings').html('<%= escape_javascript(raw(render 'listing')) %>');
$('#paginator').html('<%= escape_javascript(paginate(@listing, remote: true)) %>');

app/views/listings/new.erb
<div class="container mt-3">
  <h1 class="text-center">New Listing</h1>

  <%= form_with scope: :listing, url: listings_path, local: true do |form| %>

    <div class="mt-3">
      <h3><%= form.label :name %>:</h3>
      <%= form.text_field :name, :class => "form-control", :required => true  %>
    </div>

    <div class="mt-3">
      <h3><%= form.label :property_type %>:</h3>
      <%= form.text_field :property_type, :class => "form-control", :required => true  %>
    </div>

    <div class="mt-3">
    <h3><%= form.label :country %>:</h3>
      <%= form.text_field :country, :class => "form-control", :required => true  %>
    </div>
   
    <div class="mt-3">
      <h3><%= form.label :city %>:</h3>
      <%= form.text_field :city, :class => "form-control", :required => true  %>
    </div>

    <div class="mt-3">
      <h3><%= form.label :number_of_rooms %>:</h3>
      <%= form.text_field :room_number, :class => "form-control", :required => true  %>
    </div>
   
    <div class="mt-3">
      <h3><%= form.label :number_of_bathrooms %>:</h3>
      <%= form.text_field :bathroom_number, :class => "form-control", :required => true  %>
    </div>

     <div class="mt-3">
      <h3><%= form.label :street %>:</h3>
      <%= form.text_field :street, :class => "form-control", :required => true  %>
    </div>

    <div class="mt-3">
      <h3><%= form.label :area %>:</h3>
      <%= form.text_field :area, :class => "form-control", :required => true %>
    </div>
   
    <div class="mt-3">
      <h3><%= form.label :price %>:</h3>
      <%= form.text_field :price, :class => "form-control", :required => true  %>
    </div>

    <div class="mt-3">
      <h3><%= form.label :guest %>:</h3>
      <%= form.text_field :guest, :class => "form-control", :required => true  %>
    </div>
   
    <div class="pt-2 mt-4">
      <%= form.submit :class => "btn btn-primary" %>
      <%= link_to 'Back', listings_path, :class => "pl-2" %>
    </div>

  <% end %>
</div>

app/views/listings/show.erb
<div class="container my-4 text-capitalize">

<% if @listing.verification == true %>
  <h4>This listing is verified!</h4>
<% end %>

<div class="row">
  <div class="col-md-12">
    <% @listing.avatars.each do |avatar| %>
     <img class="listing" src="<%= avatar %>">
    <% end %>
  </div>

  <div class="col-md-4 mt-3">
    <h3 class="text-capitalize">Name:</h3>
    <p class="lead"><%= @listing.name %></p>
  </div>

  <div class="col-md-4 mt-3">
    <h3 class="text-capitalize">property type:</h3>
    <p class="lead"><%= @listing.property_type %></p>
  </div>

  <div class="col-md-4 mt-3">
    <h3 class="text-capitalize">country:</h3>
    <p class="lead"><%= @listing.country %></p>
  </div>

  <div class="col-md-4">
    <h3 class="text-capitalize">city:</h3>
    <p class="lead"><%= @listing.city %></p>
  </div>
   
  <div class="col-md-4">
    <h3 class="text-capitalize">number of rooms:</h3>
    <p class="lead"><%= @listing.room_number %></p>
  </div>

   <div class="col-md-4">
    <h3 class="text-capitalize">number of bathrooms:</h3>
    <p class="lead"><%= @listing.bathroom_number %></p>
  </div>

  <div class="col-md-4">
    <h3 class="text-capitalize">street:</h3>
    <p class="lead"><%= @listing.street %></p>
  </div>
   
  <div class="col-md-4">
    <h3 class="text-capitalize">area:</h3>
    <p class="lead"><%= @listing.area %></p>
  </div>

  <div class="col-md-4">
    <h3 class="text-capitalize">price:</h3>
    <p class="lead"><%= @listing.price %></p>
  </div>

  <div class="col-md-4">
    <h3 class="text-capitalize">guest:</h3>
    <p class="lead"><%= @listing.guest %></p>
  </div>
</div>

  <div class="col-md-4">
    <%= link_to 'Back', listings_path %> |
    <%= link_to 'Edit', edit_listing_path(@listing) %>
    <% if current_user != nil %>
      <% if current_user.access_level == "moderator" || current_user.access_level == "superadmin" && @listing.verification == false %>
        <%= link_to 'verify', verify_path(@listing) %>
      <% end %>
    <% end %>
  </div>

</div>