config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  get 'braintree/new'
  get 'listing/index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"


  get 'welcome/index'

  root 'welcome#index'

  get 'listings/index'
  resources :listings, controller: "listings" do
    resources :reservations, except: :index
  end
  resources :reservations, only:[:index]
  get '/listings/verify/:id' => 'listings#verify', as: "verify"

  post 'braintree/checkout'

  get "search" => "search#index"


  # get "/listings/:id/reservation" => "reservations#show", as: "reservation"
  # post "/listings/:id/reservation" => "reservation#crceate", as: "post_reservation"

  # resources :reservations, controller: "reservations" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, controller: "users"
  get '/users/:id' => "users#show"
end

app/models/user.rb
class User < ApplicationRecord
	 include Clearance::User
	 enum access_level: [:customer, :moderator, :superadmin]

	 has_many :listings
	 has_many :authentications, dependent: :destroy
	 has_many :reservations
	 mount_uploader :profile_picture, ProfilePictureUploader

	 def self.create_with_auth_and_hash(authentication, auth_hash)
	   user = self.create!(

	     first_name: auth_hash["info"]["first_name"],
	     last_name: auth_hash["info"]["last_name"],
	     username: auth_hash["info"]["username"],	
	     email: auth_hash["info"]["email"],
	     image: auth_hash["info"]["image"],
	     password: SecureRandom.hex(10)
	   )
	   user.authentications << authentication
	   return user
	 end

	 # grab google to access google for user data
	 def google_token
	   x = self.authentications.find_by(provider: 'google_oauth2')
	   return x.token unless x.nil?
	 end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

	def create
		@user = User.new(user_params)

    	if @user.save
      		sign_in @user
      		redirect_back_or url_after_create
    	else
      		render template: "users/new"
      end

	end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if current_user.access_level == "customer" && @user.id != current_user.id
      flash[:notice] = "This profile does not belong to you"
      redirect_back fallback_location: @user
    else
      if @user.update(user_params) 
        redirect_to @user 
      else
        render 'edit'
      end
    end
  end

	def user_from_params
    email = user_params.delete(:email)
    first_name = user_params.delete(:first_name)
    last_name = user_params.delete(:last_name)
    username = user_params.delete(:username)
    password = user_params.delete(:password)


    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.first_name = first_name
      user.last_name = last_name
      user.username = username
      user.password = password

    end
  	end

  private
  def user_params
    params.fetch(:user).permit(:username, :first_name, :last_name, :email,:password, :profile_picture)
  end 




  
end

app/views/users/_form.html.erb
<div class="form-group text-field">
  <h3><%= form.label :first_name %>:</h3>
  <%= form.text_field :first_name, :required => true, :class => "form-control" %>
</div>

<div class="form-group text-field">
  <h3><%= form.label :last_name %>:</h3>
  <%= form.text_field :last_name, :required => true, :class => "form-control" %>
</div>

<div class="form-group text-field">
  <h3><%= form.label :username %>:</h3>
  <%= form.text_field :username, :required => true, :class => "form-control" %>
</div>

<div class="form-group text-field">
  <h3><%= form.label :email %></h3>
  <%= form.text_field :email, type: 'email', :class => "form-control" %>
</div>

<div class="form-group password-field">
  <h3><%= form.label :password %></h3>
  <%= form.password_field :password, :required => true, :class => "form-control" %>
</div>

app/views/users/edit.erb
<div class="form-group text-field container mt-3">
  <h1 class="text-center">Edit Profile for <%= current_user.first_name + ' ' + current_user.last_name %></h1>

  <%= form_for @user, :html => {:multipart => true} do |form| %>
    <p>
     <h3><%= form.label :first_name %>:</h3> 
      <%= form.text_field :first_name, :class => "form-control" %>
    </p>

    <p>
      <h3><%= form.label :last_name %>:</h3>
      <%= form.text_field :last_name, :class => "form-control" %>
    </p>

    <p>
      <h3><%= form.label :username %>:</h3>
      <%= form.text_field :username, :class => "form-control" %>
    </p>
   
    <p>
      <h3><%= form.label :email %>:</h3>
      <%= form.text_field :email, :class => "form-control" %>
    </p>

    <p>
      <h3><%= form.label :profile_picture %>:</h3>
      <%= form.file_field :profile_picture %>
    </p>

    <p>
      <%= form.submit :class => "btn btn-primary my-4" %>
    </p>
  <% end %>

  <%= link_to 'Back', user_path(current_user), :class => "btn btn-primary" %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up container mt-3">
  <h2 class="text-center"><%= t(".title") %></h2>

  <%= form_for @user, :id => "sign_up" do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit :class => "btn btn-primary my-4" %>
    </div>

    <!-- <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path, :class => "btn btn-primary" %>
    </div> -->
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container mt-3">
	<div class="row">
		<div class="col-md-4">
			<%= image_tag @user.profile_picture_url.to_s, :class => "profile my-2 img-fluid" %>
		</div>
		<div class="col-md-8 text-justify">
			<p><strong>Username: </strong><%= @user.username %></p>
			<p><strong>Full Name: </strong><%= @user.first_name + " " + @user.last_name %></p>
			<p><strong>Email: </strong><%= @user.email %></p>
			<%= link_to 'Edit', edit_user_path(@user) %>
		</div>
	</div>
</div>