config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  get 'braintree/new'
  get 'listing/index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"


  get 'welcome/index'

  root 'welcome#index'

  get 'listings/index'
  resources :listings, controller: "listings" do
    resources :reservations, except: :index
  end
  resources :reservations, only:[:index]
  get '/listings/verify/:id' => 'listings#verify', as: "verify"

  post 'braintree/checkout'

  get "search" => "search#index"


  # get "/listings/:id/reservation" => "reservations#show", as: "reservation"
  # post "/listings/:id/reservation" => "reservation#crceate", as: "post_reservation"

  # resources :reservations, controller: "reservations" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, controller: "users"
  get '/users/:id' => "users#show"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :user
	belongs_to :listing

	validate :check_overlapping_dates

	before_save :compute_total_price

	def compute_total_price
		listing = Listing.find(self.listing_id)
		
		self.num_of_days = self.end_date - self.start_date
		self.total_price = self.num_of_days * listing.price
	end

	def check_overlapping_dates
		Reservation.where("listing_id = ?", self.listing_id).each do |rerservation|
			if self.overlaps?(rerservation)
				return errors.add(:overlapping_dates,"This date is not valid")
			end
		end
		return true
	end

	def overlaps?(other)
		self.start_date <= other.end_date && other.start_date <= self.end_date
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	def index
		@reservation = Reservation.page(params[:page]).per(12)

		respond_to do |format|
      format.html
      format.js { render :layout => false }
    end

	end
	
	def new
		@listing = Listing.find(params[:listing_id])
	end

	def show
		@listing = Listing.find(params[:listing_id])
		@reservation = Reservation.find(params[:id])
	end

	def create
		@listing = Listing.find(params[:listing_id])
		@reservation = Reservation.new(reservation_params)
		@reservation.user_id = current_user.id
		@reservation.listing_id = params[:listing_id]


		if @reservation.save
			#send a mail
			#run a job
			ReservationJob.perform_later(current_user.email, @listing.user.email, @reservation.id, @listing.id)
			#ReservationMailer.booking_email(current_user.email, @listing.user.email, @reservation.id, @listing.id).deliver_now
			redirect_to listing_reservation_path(params[:listing_id], @reservation)
		else
			flash[:notice] = "reservation date has been taken"
			redirect_back fallback_location: (@reservation)
		end


  		# redirect_to "/listings/#{params[:listing_id]}/reservations/#{params[:id]}"
  		
  		# rereservation_path(@reservation)
  		# 
 
	end

	def edit 
		@listing = Listing.find(params[:listing_id])
		@reservation = Reservation.find(params[:id])

	end

	def update
	  	@reservation = Reservation.find(params[:id])
	  	if current_user.access_level == "customer" && @reservation.user_id != current_user.id
	  	 	flash[:notice] = "this is not your reservation"
	  	 	redirect_back fallback_location: (@reservation)
	  	else
		  if @reservation.update(reservation_params) 
		    redirect_to listing_reservation_path(params[:listing_id], @reservation)
		  else
		    render 'edit'
		  end
		end
	end

	def destroy
	  @reservation = Reservation.find(params[:id])
	  if current_user.access_level == "customer" && @reservation.user_id != current_user.id
  	 	flash[:notice] = "this book is not yours"
  	 	redirect_back fallback_location: @reservation
  	  else
	  	@reservation.destroy
	  	redirect_back fallback_location: @reservation
	 end
  end


	private

	def reservation_params
		params.require(:reservation).permit(:start_date, :end_date,:total_price,:num_of_days)
	end 


end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_reservation.html.erb
<% @reservation.order(updated_at: :desc).each do |reservation| %>
  <div class="col-8 col-md-4 my-3">
    <div class="card" style="width: 16rem;">
      <% if reservation.listing.avatars != [] %>
        <img class="card-img-top listing" style="width: 100%" src="<%= reservation.listing.avatars[0] %>" alt="Card image cap">
      <% end %>
      <div class="card-body">
        <h5 class="card-title text-capitalize"><%= reservation.listing.name %></h5>
        <p class="card-text"><strong>Check In: </strong><span class="text-capitalize"><%= reservation.start_date %></span></p>
        <p class="card-text"><strong>Check Out: </strong><span class="text-capitalize"><%= reservation.end_date %></span></p>
        <p class="card-text"><strong>The Price: </strong><span class="text-capitalize"><%= reservation.total_price %></span></p>
        <p class="card-text"><strong>Belongs to: </strong><span class="text-capitalize"><%= reservation.user.username %></span></p>
          <div class="text-capitalize">
            <%= link_to 'Edit', edit_listing_reservation_path(reservation.listing.id, reservation), :class => "btn btn-warning btn-block" %>
            <%= link_to 'Cancel Reservation',listing_reservation_path(reservation.listing.id, reservation), :class => "btn btn-danger btn-block", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
    </div>
  </div>
<% end %>

app/views/reservations/edit.erb
<div class="container my-3">
  <h1 class="text-center"><%= @listing.name %></h1>
  
  <div>
    <% @listing.avatars.each do |avatar| %>
      <img class="listing" src="<%= avatar %>">
    <% end %>
  </div>

  <%= form_with scope: :reservation, url: listing_reservation_path(params[:listing_id],@reservation),method: :patch, local: true do |form| %>
    <h3><%= form.label :start_date %></h3>
    <input type="text" name="reservation[start_date]" value="" id="start_date" class="form-control"><br>
    <h3><%= form.label :end_date %></h3>
    <input type="text" name="reservation[end_date]" value="" id="end_date" class="form-control"><br>
    <%= form.submit :class => "btn btn-primary" %>
  <% end %>
</div>

app/views/reservations/index.erb
<div class="container my-3">
  <h1 class="text-center">All Reseervations</h1>
  
  <div id="reservation" class="row">
    <%= render "reservation" %>
  </div>

  <div id="paginator">
  	<%= paginate @reservation, :remote => true %>
  </div>
</div>

app/views/reservations/index.js.erb
$('#reservation').html('<%= escape_javascript(raw(render 'reservation')) %>');
$('#paginator').html('<%= escape_javascript(paginate(@reservation, remote: true)) %>');

app/views/reservations/new.erb
<div class="container my-3">
  <h1 class="text-center"><%= @listing.name %></h1>
  
  <div>
    <% @listing.avatars.each do |avatar| %>
      <img class="listing" src="<%= avatar %>">
    <% end %>
  </div>

  <%= form_with scope: :reservation, url: listing_reservations_path, local: true do |form| %>
    <h3><%= form.label :start_date %></h3>
    <input type="text" name="reservation[start_date]" value="" id="start_date" class="form-control"><br>
    <h3><%= form.label :end_date %></h3>
    <input type="text" name="reservation[end_date]" value="" id="end_date" class="form-control"><br>
    <%= form.submit :class => "btn btn-primary" %>
  <% end %>
</div>

app/views/reservations/show.html.erb
<div class="container my-3">
    <h1 class="text-center"><%= @listing.name %></h1>
    <div>
        <% @listing.avatars.each do |avatar| %>
          <img class="listing" src="<%= avatar %>">
        <% end %>
    </div>
    <div class="container text-center">
    	<p><strong class="text-capitalize">check in: </strong><%= @reservation.start_date %> </p>
    	<p><strong class="text-capitalize">check out: </strong><%= @reservation.end_date %> </p>
    	<p><strong class="text-capitalize">number of days: </strong><%= @reservation.num_of_days %> </p>
    	<p><strong class="text-capitalize">the total price: </strong><%= @reservation.total_price %> </p>
        <%= button_to "Make Payment", braintree_new_path, :method => :get, :class => "btn btn-primary" %>
    </div>
</div>