config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  get 'braintree/new'
  get 'listing/index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"


  get 'welcome/index'

  root 'welcome#index'

  get 'listings/index'
  resources :listings, controller: "listings" do
    resources :reservations, except: :index
  end
  resources :reservations, only:[:index]
  get '/listings/verify/:id' => 'listings#verify', as: "verify"

  post 'braintree/checkout'

  get "search" => "search#index"


  # get "/listings/:id/reservation" => "reservations#show", as: "reservation"
  # post "/listings/:id/reservation" => "reservation#crceate", as: "post_reservation"

  # resources :reservations, controller: "reservations" 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, controller: "users"
  get '/users/:id' => "users#show"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airbnb</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <!-- <a class="navbar-brand" href="#">Airbnb</a> -->
      <%= link_to "Airbnb", root_path, :class => "lead airbnb mr-2" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <!-- Put something here if needed -->
          <form action="/search" method="GET">
           <input class="form-control mr-sm-2" type="text" placeholder="Search for City" aria-label="Search" name= "city">
          </form>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li class="nav-item">
            <%= link_to "Reservations", reservations_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <p class="nav-link mb-0">Signed in as a <%= current_user.access_level %></p>
          </li>
          <li class="nav-item">
            <%= link_to "Welcome back, " + current_user.first_name + " " + current_user.last_name, user_path(current_user), :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Be a host", new_listing_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', sign_out_path, method: :delete, :class => 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in with Google', "/auth/google_oauth2", :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', sign_up_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Login', sign_in_path, :class => 'nav-link' %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <!-- /Navbar -->

  <!-- Flash messages -->
  <% flash.each do |key, value| %>
    <div class="container-fluid alert alert-<%= key %>">
      <div class="container">
        <%= value %>
      </div>
    </div>
  <% end %>
  <!-- End of Flash messages -->

  <%= yield %>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/validate-js/2.0.1/validate.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
</body>
</html>